apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-backend
  name: app-backend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: db_url
          value: jdbc:postgresql://postgres-postgresql:5433/communitter
        - name: db_username
          value: postgres
        - name: db_password
          value: postgres
        image: ghcr.io/cankuter/app-backend:latest
        imagePullPolicy: Always
        name: app-backend
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: ghcr-secret
