
name: Create and publish a Docker image

on:
  push:
    branches: ['dev']


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: app-backend

jobs:
  build-and-push-image:
    runs-on: actions-runner-set
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: app-backend:latest
          
      
      
